const firebaseConfig={apiKey:"AIzaSyCC2Jp6uz0tLFpUwRzHABPGcg1JP4H0xkg",authDomain:"james-allen-cup-2026.firebaseapp.com",projectId:"james-allen-cup-2026",storageBucket:"james-allen-cup-2026.firebasestorage.app",messagingSenderId:"131020097886",appId:"1:131020097886:web:fcc0861bc195629780a7cf"};
firebase.initializeApp(firebaseConfig);
const auth=firebase.auth(),db=firebase.firestore();
const $=s=>document.querySelector(s);
let players=[],unsubscribe=null;

const clamp=(n,min=0,max=100)=>Math.max(min,Math.min(max,Number(n)||0));
const dateText=v=>v?.toDate?new Intl.DateTimeFormat('en-PH',{dateStyle:'medium',timeStyle:'short'}).format(v.toDate()):'—';
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function challengeScores(p){const g=p.games||{};const reaction=clamp((600-(g.reaction?.avg||600))/450*100);const typing=clamp(clamp((g.typing?.wpm||0)/100*100)*.7+clamp(g.typing?.accuracy||0)*.3);const memory=clamp((g.memory?.score||0)/45*100);const duration=g.deadeye?.duration||60;const speed=clamp((35-duration)/27*100);const deadeye=clamp(clamp((g.deadeye?.hits||0)/30*100)*.55+clamp((g.deadeye?.maxCombo||0)/30*100)*.25+speed*.20);const sequence=clamp((g.sequence?.score||0)/63*100);return{reaction,typing,memory,deadeye,sequence,overall:(reaction+typing+memory+deadeye+sequence)/5}}
function statusOf(p){const n=(p.completedGames||[]).length;if(p.completed||n===5)return['COMPLETED','Completed'];if(n>0||p.briefed)return['IN_PROGRESS','In progress'];return['REGISTERED','Registered']}

$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const btn=$('#login-btn'),err=$('#login-error');btn.disabled=true;err.textContent='';try{await auth.signInWithEmailAndPassword($('#admin-email').value.trim(),$('#admin-password').value)}catch(x){console.error(x);err.textContent='Sign-in failed. Check the admin email and password.'}finally{btn.disabled=false}});
$('#logout-btn').addEventListener('click',()=>auth.signOut());
$('#search-input').addEventListener('input',render);
$('#department-filter').addEventListener('change',render);
$('#status-filter').addEventListener('change',render);
$('#export-btn').addEventListener('click',exportCSV);
$('#dialog-close').addEventListener('click',()=>$('#player-dialog').close());

function beginLiveData(){if(unsubscribe)unsubscribe();unsubscribe=db.collection('players').orderBy('registeredAt','asc').onSnapshot(s=>{players=s.docs.map(d=>({docId:d.id,...d.data()}));$('#live-status').textContent='● LIVE';render()},err=>{console.error(err);$('#live-status').textContent='● ACCESS ERROR';$('#players-body').innerHTML='<tr><td colspan="7" class="empty">Firestore access denied. Publish the supplied security rules.</td></tr>'})}
auth.onAuthStateChanged(user=>{const admin=Boolean(user&&!user.isAnonymous&&user.email);$('#login-view').classList.toggle('hidden',admin);$('#dashboard-view').classList.toggle('hidden',!admin);if(admin)beginLiveData();else{if(unsubscribe){unsubscribe();unsubscribe=null}players=[]}});

function filteredPlayers(){const q=$('#search-input').value.trim().toLowerCase(),dept=$('#department-filter').value,status=$('#status-filter').value;return players.filter(p=>{const st=statusOf(p)[0];return(!q||`${p.name||''} ${p.cupID||''}`.toLowerCase().includes(q))&&(dept==='ALL'||p.department===dept)&&(status==='ALL'||st===status)})}
function render(){const completed=players.filter(p=>p.completed||(p.completedGames||[]).length===5).length;const progress=players.filter(p=>{const n=(p.completedGames||[]).length;return !p.completed&&n>0}).length;$('#metric-registered').textContent=players.length;$('#metric-progress').textContent=progress;$('#metric-completed').textContent=completed;$('#metric-rate').textContent=players.length?`${Math.round(completed/players.length*100)}%`:'0%';const list=filteredPlayers();$('#visible-count').textContent=`${list.length} shown`;$('#players-body').innerHTML=list.length?list.map(playerRow).join(''):'<tr><td colspan="7" class="empty">No matching competitors.</td></tr>';document.querySelectorAll('.view-btn').forEach(b=>b.addEventListener('click',()=>openPlayer(b.dataset.id)));renderLeaderboard()}
function playerRow(p){const n=(p.completedGames||[]).length,[key,label]=statusOf(p);return`<tr><td><strong>${esc(p.cupID||'—')}</strong></td><td>${esc(p.name||'Unnamed')}</td><td>${esc(p.department||'—')}</td><td class="progress-cell"><div class="progress-line"><div class="progress-track"><i style="width:${n/5*100}%"></i></div><span>${n}/5</span></div></td><td><span class="status ${key==='COMPLETED'?'completed':key==='IN_PROGRESS'?'progress':'registered'}">${label}</span></td><td>${esc(dateText(p.updatedAt||p.registeredAt))}</td><td><button class="view-btn" data-id="${esc(p.docId)}">VIEW</button></td></tr>`}
function renderLeaderboard(){const done=players.filter(p=>p.completed||(p.completedGames||[]).length===5).map(p=>({...p,scoreSet:challengeScores(p)})).sort((a,b)=>b.scoreSet.overall-a.scoreSet.overall);$('#leaderboard-body').innerHTML=done.length?done.map((p,i)=>`<tr><td class="rank">${i+1}</td><td>${esc(p.name)}</td><td>${esc(p.department)}</td><td class="score"><strong>${p.scoreSet.overall.toFixed(1)}</strong></td><td class="score">${p.scoreSet.reaction.toFixed(1)}</td><td class="score">${p.scoreSet.typing.toFixed(1)}</td><td class="score">${p.scoreSet.memory.toFixed(1)}</td><td class="score">${p.scoreSet.deadeye.toFixed(1)}</td><td class="score">${p.scoreSet.sequence.toFixed(1)}</td></tr>`).join(''):'<tr><td colspan="9" class="empty">No completed competitors yet.</td></tr>'}
function openPlayer(id){const p=players.find(x=>x.docId===id);if(!p)return;const g=p.games||{},s=challengeScores(p);$('#dialog-name').textContent=p.name||'Player';$('#dialog-content').innerHTML=`<div class="detail-meta"><div class="detail-box"><small>CUP ID</small><strong>${esc(p.cupID||'—')}</strong></div><div class="detail-box"><small>DEPARTMENT</small><strong>${esc(p.department||'—')}</strong></div><div class="detail-box"><small>PROGRESS</small><strong>${(p.completedGames||[]).length} / 5</strong></div><div class="detail-box"><small>OVERALL NORMALIZED</small><strong>${s.overall.toFixed(1)}</strong></div></div><div class="game-grid"><div class="detail-box"><small>REFLEX PROTOCOL</small><strong>${g.reaction?`${esc(g.reaction.avg)} ms`:'Not completed'}</strong></div><div class="detail-box"><small>TYPING RUSH</small><strong>${g.typing?`${esc(g.typing.wpm)} WPM · ${esc(g.typing.accuracy)}%`:'Not completed'}</strong></div><div class="detail-box"><small>MEMORY MATRIX</small><strong>${g.memory?`${esc(g.memory.score)} / 45`:'Not completed'}</strong></div><div class="detail-box"><small>DEADEYE</small><strong>${g.deadeye?`${esc(g.deadeye.hits)} hits · ${esc(g.deadeye.misses)} misses · combo ${esc(g.deadeye.maxCombo)}`:'Not completed'}</strong></div><div class="detail-box"><small>SEQUENCE RECALL</small><strong>${g.sequence?`${esc(g.sequence.score)} / 63`:'Not completed'}</strong></div><div class="detail-box"><small>LAST UPDATE</small><strong>${esc(dateText(p.updatedAt||p.registeredAt))}</strong></div></div>`;$('#player-dialog').showModal()}
function exportCSV(){const headers=['Cup ID','Name','Department','Completed Games','Status','Reaction Avg ms','Typing WPM','Typing Accuracy','Memory Score','Deadeye Hits','Deadeye Misses','Deadeye Max Combo','Deadeye Duration','Sequence Score','Normalized Overall','Registered At','Updated At'];const rows=players.map(p=>{const g=p.games||{},s=challengeScores(p);return[p.cupID,p.name,p.department,(p.completedGames||[]).length,statusOf(p)[1],g.reaction?.avg,g.typing?.wpm,g.typing?.accuracy,g.memory?.score,g.deadeye?.hits,g.deadeye?.misses,g.deadeye?.maxCombo,g.deadeye?.duration,g.sequence?.score,s.overall.toFixed(1),dateText(p.registeredAt),dateText(p.updatedAt)]});const csv=[headers,...rows].map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`James-Allen-Cup-2026-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)}
